version: '3.8'

services:
    #--Redis--#
    redis:
        image: redis
        ports:
            - '6379:6379'
        restart: always
    #--Stream--#
    stream:
        image: segment/fake-event-stream
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_CHANNEL=events
            - EVENTS_PER_SECOND=10
        links:
            - redis
    #--Back-end app--#
    server:
        environment:
            - PORT=2502
            - HOST=0.0.0.0
        container_name: testtask-server
        restart: always
        build:
            context: ../../server/
            dockerfile: Dockerfile
        ports:
            - '2502:2502'
            - '2501:2501'
        links:
            - redis
        depends_on:
            - redis
    #--Front-end app--#
    # client:
    #     container_name: testtask-client
    #     restart: always
    #     build:
    #         context: ../../client/
    #         dockerfile: Dockerfile
    #     ports:
    #         - '2500:2500'
    #     links:
    #         - server
    #     depends_on:
    #         - server
